title: Hello!
author: Rebecca Lee
email: rmlee@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  A website encompassing information about myself.
theme: minima

# social links
instagram_username: r.e.m.e.l.e # DO NOT include the @ character, or else the build will fail!
github_username:  remelee # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
